config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root :to => "merchants#index"
  devise_for :merchants
  # Routes for the Merchant resource:
  # READ
  get "/merchants", :controller => "merchants", :action => "index"
  get "/merchants/:id", :controller => "merchants", :action => "show"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/merchant.rb
class Merchant < ApplicationRecord
  # Direct associations

  # Indirect associations

  # Validations

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_merchant!

  protect_from_forgery with: :exception
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>OnlyOneTable1476459047</title>


  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  <style>
    /* Only necessary if you are using navbar-fixed-top */
    body {
      padding-top: 60px;
    }
  </style>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a href="/" class="navbar-brand">OnlyOneTable1476459047</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/merchants">Merchants</a></li>
          <li><a href="/rails/info">Sitemap</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if current_merchant.present? %>
            <li>
              <a href="/merchants/edit">
                <%= current_merchant.username %>
              </a>
            </li>

            <li>
              <a href="/merchants/sign_out" data-method="delete" rel="nofollow">
                Sign Out
              </a>
            </li>
          <% else %>
            <li>
              <a href="/merchants/sign_up">
                Sign Up
              </a>
            </li>

            <li>
              <a href="/merchants/sign_in">
                Sign In
              </a>
            </li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-dismissable alert-warning">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/merchants/index.html.erb
<div class="page-header">
  <h1>
    Merchants
    <a href="/merchants/new" class="btn btn-lg btn-success">New Merchant</a>
  </h1>
</div>

<div class="row">
  <div class="col-md-12">
    <table class="table table-striped table-hover">
      <tr>
        <th>Email</th>
        <th>Password</th>
        <th>Actions</th>
      </tr>

      <% @merchants.each do |merchant| %>
      <tr>
        <td><%= merchant.email %></td>
        <td><%= merchant.password %></td>
        <td>
          <a href="/merchants/<%= merchant.id %>" class="btn btn-primary">Show</a>
          <a href="/merchants/<%= merchant.id %>/edit" class="btn btn-warning">Edit</a>
          <a href="/delete_merchant/<%= merchant.id %>" class="btn btn-danger" rel="nofollow">Delete</a>
        </td>
      </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/merchants/show.html.erb
<div class="page-header">
  <h3>Merchant #<%= @merchant.id %></h3>
</div>

<div class="row">
  <div class="col-md-12">
    <dl class="dl-horizontal">
      <dt>Email</dt>
      <dd><%= @merchant.email %></dd>

      <dt>Password</dt>
      <dd><%= @merchant.password %></dd>

    </dl>

    <div class="btn-group btn-group-justified">
      <a href="/merchants" class="btn btn-primary">
        Back
      </a>
      <a href="/merchants/<%= @merchant.id %>/edit" class="btn btn-warning">
        Edit
      </a>
      <a href="/delete_merchant/<%= @merchant.id %>" class="btn btn-danger" rel="nofollow">
        Delete
      </a>
    </div>
  </div>
</div>